################################
# Dune module information file #
################################

#Name of the module
Module: dune-gesis
Version: 1.0.0
Maintainer: ngo@eclipso.de
#depending on
#
Depends: dune-common (>= 2.3.1) dune-istl (>= 2.3.1) dune-geometry (>= 2.3.1) dune-grid (>= 2.3.1) dune-localfunctions (>= 2.3.1) dune-typetree (>= 2.3.1) dune-pdelab (>= 2.0.0)
#
Suggests: dune-alugrid (>= 2.3)
# dune-alugrid is required only for the 3D adaptive forward transport equation solver with load-balancing.
# It is not needed by the inversion scheme that runs only on YASP grid.
#


