################################
# Dune module information file #
################################

#Name of the module
Module: dune-gesis
Version: 1.0.1
Maintainer: adrian.ngo@iwr.uni-heidelberg.de
#depending on
Depends: dune-common dune-istl dune-geometry dune-grid dune-localfunctions dune-typetree dune-pdelab

# Add dune-alugrid if you want to try the 3D adaptive forward transport equation solver with load-balancing:
#Depends: dune-common dune-istl dune-geometry dune-grid dune-alugrid dune-localfunctions dune-typetree dune-pdelab

